name: main-pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-frontend-build-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Verify Java version
        run: java -version

      - name: Build Backend
        run: |
          cd backend
          mvn clean install

      - name: Test Backend with JaCoCo
        run: |
          cd backend
          mvn test
          mvn jacoco:report

      - name: Build Backend package
        run: |
          cd backend
          mvn -B package --file pom.xml

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test
        env:
          CI: true

  sonarcloud-analysis:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    needs: backend-frontend-build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Verify Java version
        run: java -version

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ./backend
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=sqs-projekt_backend \
            -Dsonar.organization=sqs-projekt \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      - name: Analyze frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd frontend
          npx sonar-scanner \
            -Dsonar.projectKey=sqs-projekt_frontend \
            -Dsonar.organization=sqs-projekt \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=src \
            -Dsonar.exclusions=src/**/__tests__/**,src/**/tests/** \
            -Dsonar.tests=tests \
            -Dsonar.test.inclusions=tests/**/*.test.js,tests/**/*.spec.js \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info


  docker-container-build-push:
    needs: [backend-frontend-build-test, sonarcloud-analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Steps to build and push docker container images go here
