name: main-pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-frontend-build-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Verify Java version
        run: java -version

      - name: Build Backend
        run: |
          cd backend
          mvn clean install
          
      - name: Test Backend
        run: |
          cd backend
          mvn test
      - name: Build Backend package
        run: |
          cd backend
          mvn -B package --file pom.xml
      - name: Run Backend in Backgroung
        run: |
          cd backend

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test
        env:
          CI: true
