name: main-pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-frontend-build-test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Verify Java version
        run: java -version

      - name: Build Backend
        run: |
          cd backend
          ./mvnw clean install
          
      - name: Test Backend
        run: |
          cd backend
          ./mvnw test
          
      - name: Run Backend
        run: |
          cd backend
          ./mvnw spring-boot:run

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run React Frontend
        run: |
          cd frontend
          npm run build

      - name: Run frontend tests
        run: |
          cd frontend
          npm test
        env:
          CI: true
